# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7c89ef217b2570b00597507557486908741ea748dac2f9f28fbb9dc2295035fc21f58386626072f8b55ffd12b006cae409c065d2acafcaa317865a4499251923

test:
  secret_key_base: 6a074e1d697bfa0b177cbc0ccce4ad78c60145fe5c127d23698408f8a4c8f1f1156bb88c733479af1fac7ed1e06b4f1897d3e0866423c07edf0c6731d9c7962c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

# Twitter API
CONSUMER_KEY: YjTFlm1ePPwvE5f2d0KIywtaR
CONSUMER_SECRET: M7RRsSx1Ku8X05r5lTVnAJ6rUu1OXYMcddoh4s6SjWXVrVnNVh
ACCESS_TOKEN: 709420247837773824-A7reZNzbN8AdOUm3oEHHjbqf9PmD3xd
ACCESS_TOKEN_SECRET: 47BF8Mud8oXz0htnrZP3IEjOQ95lIEa4wPpFA7bc0fMK7